### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by sojusnik** [oleid/gnome-shell-teatime#10]
Hey,

I think, that the following features would make this extension even more useful:
1. Implementing a way to stop the current countdown
2. A configurable sound should play at the end of a countdown
3. A shortcut to open the extensions' time input window, that will allow you to type in the desired countdown time afterwards and press enter, so that a new countdown will start.

Best wishes!

**Comment by sojusnik** [comment]
Any progress on the keyboard shortcut for the countdown field?

Ideally, other time formats than mm:ss should be implemented as well, like:
4s
4sec
4secs
5m
5min
5mins
and their combination, f.i.: 5m30s

When typing a number without ":", then this number should be counted as minutes, so that typing only 3 should start a 3 minutes timer.

**Comment by oleid** [comment]
No, I'm sorry. Due to some issues, I'm not running gnome-shell at the moment on my desktop, thus I didn't work on it at the moment. But if you send patches, I'm happy to review them...
