### ISSUE TITLE
Icon is bigger than all other icons / Shadow

### ISSUE THREAD

**Issue by kelunik** [oleid/gnome-shell-teatime#17]
Icon and progress circle are bigger than other icons:
![](http://i.imgur.com/27JDNjr.png)

`icon-shadow` nor `text-shadow` are applied.

The missing padding is already discussed in #7.

**Comment by oleid** [comment]
Padding should be fixed in the theme_awareness branch. Yet, I still can't detect any shadow. Could you point me to a theme, where the shadow is obvious?

I guess implementing the shadow is simple, I just need to know how it should look like.

**Comment by kelunik** [comment]
If you want an obvious shadow, just increase it here from `0.2` to `1`:
https://github.com/kelunik/gnome-shell-theme/blob/master/src/gnome-shell/gnome-shell.css#L460

You can package the theme using `zip.sh`.

**Comment by oleid** [comment]
Okay, now I can see shadows. But drawing shadows seems not to be as simple as I thought. There's not even a blur function in cairo and I'd like to avoid implementing one in JS. I'll investigate what's the best way to add shadows and keep the animation.

**Comment by kelunik** [comment]
I'm not sure, but I don't think this should be done by the extension. I think this is the job of gnome-shell itself.

**Comment by oleid** [comment]
Yes, I concur.  If it was possible to fill a St.Icon with something you draw in a St.DrawingArea, we'd be done... But I couldn't find a way, so far..

Maybe the gnome-shell mailing list has an answer...
