### ISSUE TITLE
Teatime leaves open sink

### ISSUE THREAD

**Issue by MedicMomcilo** [oleid/gnome-shell-teatime#20]
Hi, this extension is pretty usefull!

One minor thing I noticed is whenever sound is played there is a sink left open which can be viewed in pavucontrol or similar programs. This occurs for every timer, each time creating new sink.

As I am using Volume mixer extension, this can get pretty messy.

Is it possible to fix this?

Keep up the great work people! :)

**Comment by oleid** [comment]
You're right. I'm wondering, why I didn't notice that before. Or maybe it's a change in Gnome-Shell 3.14 (I guess you're using this one?).

I'll try to find out what's wrong...

**Comment by MedicMomcilo** [comment]
Thanks for investigating.

I am indeed using Gnome Shell 3.14 on Fedora 21 x86_64

**Comment by oleid** [comment]
The issue should be fixed with the latest commit.
