### ISSUE TITLE
Image of pot in notification is blur and overstretched in GNOME 3.16

### ISSUE THREAD

**Issue by Mno-hime** [oleid/gnome-shell-teatime#22]
Image of pot in notification is blur and overstretched in GNOME 3.16:

![pot](https://cloud.githubusercontent.com/assets/4632197/7910059/8ecbd490-0851-11e5-80a7-e2f65f128c36.png)

**Comment by oleid** [comment]
Hey, thanks for reporting the problem. Could you add some more information, e.g. your distribution and your themes? I don't see the problem on my gnome 3.16.

**Comment by Mno-hime** [comment]
It's Fedora 22, default theme. Disabled all extensions and the problem is still present. No other configuration I know of which might be relevant.

**Comment by oleid** [comment]
Interesting. I guess you are using the latest git version? I'm asking, because I don't have an icon there...

**Comment by Mno-hime** [comment]
I think I use the extensions.g.o version, that is 18.

**Comment by oleid** [comment]
Okay, should be in sync with the github version. Could it be, that you have an icon called somewhere left on your disk in $HOME/.local/share/gnome-shell/extensions/TeaTime@oleid.mescharet.de ?

For some reason I could never resolve, the icon is completely stretched in gnome-shell-3.16. Therefore, I rewrote the whole drawing stuff in JS and removed the SVG icon file.

**Comment by Mno-hime** [comment]
Right. So there are some images in my TeaTime... folder, so I removed
it, installed fresh copy from ext.g.o. And this is list of files in the
TeaTime... folder:

TeaTime@oleid.mescharet.de/
TeaTime@oleid.mescharet.de/schemas
TeaTime@oleid.mescharet.de/schemas/gschemas.compiled
TeaTime@oleid.mescharet.de/locale
TeaTime@oleid.mescharet.de/locale/fr
TeaTime@oleid.mescharet.de/locale/fr/LC_MESSAGES
TeaTime@oleid.mescharet.de/locale/fr/LC_MESSAGES/TeaTime.mo
TeaTime@oleid.mescharet.de/locale/de
TeaTime@oleid.mescharet.de/locale/de/LC_MESSAGES
TeaTime@oleid.mescharet.de/locale/de/LC_MESSAGES/TeaTime.mo
TeaTime@oleid.mescharet.de/locale/es
TeaTime@oleid.mescharet.de/locale/es/LC_MESSAGES
TeaTime@oleid.mescharet.de/locale/es/LC_MESSAGES/TeaTime.mo
TeaTime@oleid.mescharet.de/stylesheet.css
TeaTime@oleid.mescharet.de/extension.js
TeaTime@oleid.mescharet.de/utils.js
TeaTime@oleid.mescharet.de/prefs.js
TeaTime@oleid.mescharet.de/README.md
TeaTime@oleid.mescharet.de/icon.js
TeaTime@oleid.mescharet.de/metadata.json
TeaTime@oleid.mescharet.de/data
TeaTime@oleid.mescharet.de/data/cup05.png
TeaTime@oleid.mescharet.de/data/cup07.png
TeaTime@oleid.mescharet.de/data/cup02.png
TeaTime@oleid.mescharet.de/data/cup13.png
TeaTime@oleid.mescharet.de/data/cup10.png
TeaTime@oleid.mescharet.de/data/cup19.png
TeaTime@oleid.mescharet.de/data/cup16.png
TeaTime@oleid.mescharet.de/data/cup09.png
TeaTime@oleid.mescharet.de/data/cup21.png
TeaTime@oleid.mescharet.de/data/cup23.png
TeaTime@oleid.mescharet.de/data/cup03.png
TeaTime@oleid.mescharet.de/data/cup06.png
TeaTime@oleid.mescharet.de/data/cup20.png
TeaTime@oleid.mescharet.de/data/cup12.png
TeaTime@oleid.mescharet.de/data/cup15.png
TeaTime@oleid.mescharet.de/data/cup11.png
TeaTime@oleid.mescharet.de/data/cup00.png
TeaTime@oleid.mescharet.de/data/cup14.png
TeaTime@oleid.mescharet.de/data/cup17.png
TeaTime@oleid.mescharet.de/data/cup01.png
TeaTime@oleid.mescharet.de/data/cup04.png
TeaTime@oleid.mescharet.de/data/cup22.png
TeaTime@oleid.mescharet.de/data/cup18.png
TeaTime@oleid.mescharet.de/data/cup08.png

It looks basically the same in as my original installation.

**Comment by oleid** [comment]
Strange. But then, where does it pull the SVG icon from?  I have to dig
further...

**Comment by Mno-hime** [comment]
What about /usr/share/icons/hicolor/scalable/apps/utilities-teatime.svg? It does not belong to any RPM package and I have some memory of me manually installing this image because of your extension since you didn't know how to do it in the installation hook back then (or perhaps a false memory? :) ). Can't upload it since GitHub won't let me, but with the icon removed the notification looks good (i.e. no overstretched icon, though I'd expect correctly enlarged icon there) -- is it intended to be this way?

**Comment by oleid** [comment]
Yep, you're right. I recall that issue. So that's the difference! :)

In an ideal world, we'd have an icon in the notification, but since I
really don't know what changed between gnome-shell-3.14 and 3.16 that
might stretch the icon, I switched to manually drawing the icon via
cairo and removed the svg file. I think no icon in the notification is
better than an ugly one ;)

**Comment by Mno-hime** [comment]
Right :). Thanks.
