### ISSUE TITLE
3.18, please

### ISSUE THREAD

**Issue by rudrab** [oleid/gnome-shell-teatime#23]
Hi,
I used to use your app too much. Kindly consider updating it for 3.18

**Comment by oleid** [comment]
Hey, I'm not on 3.18, yet. Assuming there are not too many changes, simply editing metadata.json in the extension folder in $HOME/.local/share/gnome-shell/extensions should do the trick. Could you test that?

**Comment by rudrab** [comment]
Hi,
Thanks for your prompt reply. I have a new installation and cant install it from gnome site. But I have done it from git repo (here), and make local-install, make zip (with 3.18 in metadata) is working perfectly.

**Comment by oleid** [comment]
Okay, thanks for testing. I updated the metadata file in the git repo and will submit the latest version to the extension page. closing
