### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by oleid** [oleid/gnome-shell-teatime#24]
From the gnome-shell-extensions webpage:

```
zwarag: Could you make it svg so that it may scale on HiDPI screens? 
        Otherwise it's a really great Extension.
```

I'm not sure what's different on HiDPI screens. The tea pot is actually a SVG file, but it's drawn manually using cairo. Need to investigate.

**Comment by naanoo** [comment]
This is, what it looks like on a 5K Display. (too high, too small)

![bildschirmfoto von 2016-11-11 10-35-28](https://cloud.githubusercontent.com/assets/16617292/20210582/9f3e1172-a7fa-11e6-9d2e-1618e70f5166.png)

**Comment by fbruetting** [comment]
Not sure, but shouldn’t the property `icon_name` be used in `PanelMenu.Button`, instead of `logo`?

**Comment by jspitz** [comment]
It is correct if you double the size value passed to `TwoColorIcon`, i.e.
`this._logo     = new Icon.TwoColorIcon(48, Icon.TeaPot);`
and
`this._graphicalTimer = new Icon.TwoColorIcon(48, Icon.Pie);`

But of course, this should be done automatically (maybe based on `Gdk.Window.prototype.get_scale_factor()`?)

**Comment by fbruetting** [comment]
There is no need for adding resolution specific code if just the standard API is used. Seems that this isn’t the case, since there also is no padding around it. I implemented almost the same some time ago end it resizes perfectly – but I did this inside the system status menu:

```
const Indicator = new Lang.Class
({
	Name:		'StatusIndicator',
	Extends:	PanelMenu.SystemIndicator,
	
	_init: function ()
	{
		// Call parent constructor
		this.parent ();
		
		[...]
		
		this._indicator			= this._addIndicator ();
		this._indicator.icon_name	= 'user-available';
		this._indicator.style_class	= 'system-status-icon'
		
		[...]
	},

	destroy: function ()
	{
		this.indicators.destroy ();
	},
});
```

**Comment by oleid** [comment]
@fbruetting:  Before I used a custom implementation of the Panel icon, scaling worked. However, due to custom drawing needs, I don't see how I can get around implementing the scaling manually.

@jspitz: It took me a while to get the proper scaling factor via accessible API. Sadly, St doesn't export it as willingly as Gtk. But I found a way to get the factor via the theme nodes API.

For anyone interested in automatic scaling: please test. I pushed some new code which should work.

**Comment by fbruetting** [comment]
@oleid  You don’t need to rescale at all! Just use my code (but use the appropriate button instead of my `PanelMenu.SystemIndicator`). I review the new code, if I manage to find some time this week.

**Comment by oleid** [comment]
@fbruetting: Correct me if I'm wrong, but your code only works as advertised when using St.Icon?

**Comment by fbruetting** [comment]
This could be the case. I don’t understand JS that much, as I try to avoid this insaneness where possible. But since you just use a teapot icon, why not use this St.Icon?

**Comment by oleid** [comment]
I used St.Icon before and scaling worked fine (probably except for the animated disk). But since then, people asked for using inverted colors for the animated disk and the teapot. Thus, I manually implemented drawing (cf.f the comment header in src/icon.js).

The way I understand the problem, St.Icon is automatically resized to max(Indicator.width, Indicator.height). But a simple DrawingArea isn't. So if I'd catch the resize event of the top level container and set the size of the DrawingArea accordingly, the work-around of using the display scale_factor wouldn't be needed. But considering the documentation is lacking and debugging shell extensions is as pleasant as drilling a hole into one's own skull, I didn't find the required information, yet. :/

**Comment by fbruetting** [comment]
Ok, the resizing isn’t that critical, but the missing padding is more striking. ;)

**Comment by fbruetting** [comment]
Now the tart animation is oval instead of circular. Please fix this via the default way everyone uses, and don’t do any weird modifications…

**Comment by oleid** [comment]
There is no default way AFAIK and I've no time working on this ATM, I'm sorry.

**Comment by fbruetting** [comment]
Ok, maybe I get to it by the end of the holidays this week…
