### ISSUE TITLE
Add a "Stop Timer" menu option.

### ISSUE THREAD

**Issue by kgorbi** [oleid/gnome-shell-teatime#44]
Useful option to cancel currently running timeout.

**Comment by kgorbi** [comment]
I have a patch ready for that -> how can I share it with you?

**Comment by oleid** [comment]
That's cool!
You could i.e send a pull request, after forking the code and pushing the changes to your fork. Be sure to run 

beautify-code.sh

before comitting your changes to keep the diff clean.

**Comment by oleid** [comment]
Merged via #45.
