### ISSUE TITLE
2nd Enter is not working

### ISSUE THREAD

**Issue by Demetri0** [oleid/gnome-shell-teatime#46]
When I input value and press the main Enter on a keyboard - it works fine, but if I use Enter near numpad - it is not working.

Ubuntu 18.04.1 LTS
GNOME 3.28.2

**Comment by vanous** [comment]
Same here, or actually bit worse... i only have one enter on my laptop and it is not working...

**Comment by zeners** [comment]
also fixed with commit #49

**Comment by oleid** [comment]
#49 was merged
