### ISSUE TITLE
Theming issue when using non-black background in gnome-shell-- was: Display remaining time as numbers

### ISSUE THREAD

**Issue by sojusnik** [oleid/gnome-shell-teatime#7]
Hi!
Thanks for this extension!
Would be great, if you could implement an option to show the remaining time as numbers, like it's done by the pomodoro extension¹. The circle looks imho a little bit out of place, as you can see for example:

http://i.imgur.com/hP1icGY.png

---

¹https://github.com/codito/gnome-shell-pomodoro

**Comment by oleid** [comment]
In the theme_awareness branch, the margin is now read from the current theme ...
